# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jogo da Memoria' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jogo da Memoria
  pod 'SnapKit', '~> 5.6.0'

  target 'Jogo da MemoriaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Jogo da MemoriaUITests' do
    # Pods for testing
  end

end
